---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-pod-terminator
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-pod-terminator
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-pod-terminator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-pod-terminator
subjects:
  - kind: ServiceAccount
    name: kube-pod-terminator
    namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-pod-terminator
  name: kube-pod-terminator
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-pod-terminator
      deployment: kube-pod-terminator
  template:
    metadata:
      labels:
        app: kube-pod-terminator
        deployment: kube-pod-terminator
    spec:
      serviceAccountName: kube-pod-terminator-sa
      containers:
        - image: 'docker.io/bilalcaliskan/kube-pod-terminator:latest'
          command: ["./main"]
          args: [
              "--namespace", "default",
              "--ticker-interval-minutes", "10",
              "--in-cluster=true",
              "--kubeconfig-paths", "/opt/cluster1-config.yaml,/opt/cluster2-config.yaml,/opt/cluster3-config.yaml",
              "--one-shot=false"
          ]
          imagePullPolicy: Always
          name: kube-pod-terminator
          volumeMounts:
            - name: cluster1-config
              mountPath: /opt/cluster1-config.yaml
              subPath: cluster1-config.yaml
            - name: cluster2-config
              mountPath: /opt/cluster2-config.yaml
              subPath: cluster2-config.yaml
            - name: cluster3-config
              mountPath: /opt/cluster3-config.yaml
              subPath: cluster3-config.yaml
      volumes:
        - name: cluster1-config
          configMap:
            name: cluster1-config
        - name: cluster2-config
          configMap:
            name: cluster2-config
        - name: cluster3-config
          configMap:
            name: cluster3-config
