---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-pod-terminator-sa
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-pod-terminator-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-pod-terminator-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-pod-terminator-role
subjects:
  - kind: ServiceAccount
    name: kube-pod-terminator-sa
    namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-pod-terminator
  name: kube-pod-terminator
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-pod-terminator
      deployment: kube-pod-terminator
  template:
    metadata:
      labels:
        app: kube-pod-terminator
        deployment: kube-pod-terminator
    spec:
      serviceAccountName: kube-pod-terminator-sa
      containers:
        - image: 'docker.io/bilalcaliskan/kube-pod-terminator:latest'
          command: ["./main"]
          args: [
              "--namespace", "default",
              "--tickerIntervalMin", "10",
              "--inCluster", "true"
          ]
          imagePullPolicy: Always
          name: kube-pod-terminator
